#

- name: Touch the log file
  become: True
  file:
    path: "{{ unbound_logfile }}"
    state: touch
    mode: "u=rw,g=r,o=r"
    owner: unbound
    group: unbound
    modification_time: preserve
    access_time: preserve

- name: Add the apparmor permissions
  become: True
  ansible.builtin.lineinfile:
    path: /etc/apparmor.d/local/usr.sbin.unbound
    line: "/var/log/unbound.log rw,"
    create: yes
  notify: restart apparmor