---

- name: restart unbound
  become: true
  service:
    name: "{{ unbound_service_name }}"
    state: "{{ unbound_reloaded_state }}"

- name: restart apparmor
  become: true
  command: apparmor_parser -r /etc/apparmor.d/usr.sbin.unbound
  when: ansible_virtualization_type != "lxc"
# vim: set ts=2 sw=2:
